# Generated by Django 5.1 on 2024-08-20 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mail', models.EmailField(max_length=254)),
                ('description', models.TextField(max_length=200)),
                ('event_date', models.DateField()),
                ('event_time', models.DateTimeField()),
            ],
        ),
    ]
