# Generated by Django 5.1 on 2024-08-20 06:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='description',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='mail',
            new_name='E_mail',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='event_date',
            new_name='Event_date',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='event_time',
            new_name='Event_time',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='name',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='Quantity',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)]),
            preserve_default=False,
        ),
    ]
