# Generated by Django 5.1 on 2024-08-20 14:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_description_reservation_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='Name',
        ),
        migrations.AddField(
            model_name='reservation',
            name='number',
            field=models.IntegerField(default=9828222222, verbose_name='Phone Number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Description',
            field=models.TextField(max_length=200, verbose_name='Any Special Request'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='E_mail',
            field=models.EmailField(max_length=254, verbose_name='E_Mail'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Event_date',
            field=models.DateField(verbose_name='year/month/day'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Event_time',
            field=models.TimeField(verbose_name='hour/minute/second'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='Quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(50)], verbose_name='No.of People'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='name',
            field=models.CharField(default=1233344444, max_length=200, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
