# Generated by Django 5.0.6 on 2024-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=25)),
                ('Description', models.TextField(max_length=200, verbose_name='Your message Request')),
                ('image', models.ImageField(blank=True, null=True, upload_to='imagess/')),
            ],
        ),
    ]
