# Generated by Django 5.0.6 on 2024-08-27 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_view',
        ),
    ]
